os:
	- osx
language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

#before install:


# Install packages
install:
# Setup anaconda
	#Linux way
  #- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #osx way
  - curl http://repo.continuum.io/miniconda/Miniconda-3.5.5-MacOSX-x86_64.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - ./requirements/requirements.sh

# command to run tests, e.g. python setup.py te
script:  python test.py